name: Run Basic Train

on: [push]

jobs:
  run_train_nsfp:
    runs-on: ubuntu-latest
    container:
      image: kylevedder/zeroflow_bucketed

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup env
      run: |
        ./tests/setup.sh
    
    - name: Run NSFP E2E one step
      run: |
        python test_pl.py tests/configs/nsfp_one_step.py --cpu

  run_competition_bundler:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tqdm

    - name: Setup Files
      run: |
        ./tests/setup.sh

    - name: Validate Competition Submit
      run: |
        ./tests/validate_competition_submit.sh

