name: Run Basic Train

on: [push]

jobs:

  prepare_runner:
    runs-on: ubuntu-latest

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'

  # Runs on base system
  run_competition_bundler:
    runs-on: ubuntu-latest
    needs: prepare_runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tqdm

    - name: Setup Files
      run: |
        ./tests/setup.sh

    - name: Validate Competition Submit
      run: |
        ./tests/validate_comp_submit/run.sh

  # Runs inside docker image
  # Docker image pull does not cache, so running these in parallel kills the machine.
  run_container_tests:
    runs-on: ubuntu-latest
    container:
      image: kylevedder/zeroflow_bucketed_cpu
    needs: prepare_runner
    

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup env
      run: |
        ./tests/setup.sh

    - name: Run constant baseline 
      run: |
        ./tests/constant_baseline/run.sh
    
    - name: Run NSFP E2E one step
      run: |
        ./tests/nsfp_one_step/run.sh
  
  
  

